# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ticketing.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ticketing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fticketing.proto\x12\tticketing\x1a\x1fgoogle/protobuf/timestamp.proto\"/\n\x15GetTicketPriceRequest\x12\x16\n\x0eticket_type_id\x18\x01 \x01(\t\"F\n\x16GetTicketPriceResponse\x12\x12\n\x05\x65rror\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x0e\n\x06\x61mount\x18\x02 \x01(\tB\x08\n\x06_error\"1\n\x17\x43heckReservationRequest\x12\x16\n\x0ereservation_id\x18\x01 \x01(\t\"\x9a\x01\n\x0bReservation\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12.\n\ncreated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nexpires_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06status\x18\x05 \x01(\t\"u\n\x18\x43heckReservationResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x12\r\n\x05valid\x18\x02 \x01(\x08\x12+\n\x0breservation\x18\x03 \x01(\x0b\x32\x16.ticketing.Reservation\x12\r\n\x05\x65rror\x18\x04 \x01(\t2\xca\x01\n\x14GrpcTicketingService\x12[\n\x10\x43heckReservation\x12\".ticketing.CheckReservationRequest\x1a#.ticketing.CheckReservationResponse\x12U\n\x0eGetTicketPrice\x12 .ticketing.GetTicketPriceRequest\x1a!.ticketing.GetTicketPriceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ticketing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETTICKETPRICEREQUEST']._serialized_start=63
  _globals['_GETTICKETPRICEREQUEST']._serialized_end=110
  _globals['_GETTICKETPRICERESPONSE']._serialized_start=112
  _globals['_GETTICKETPRICERESPONSE']._serialized_end=182
  _globals['_CHECKRESERVATIONREQUEST']._serialized_start=184
  _globals['_CHECKRESERVATIONREQUEST']._serialized_end=233
  _globals['_RESERVATION']._serialized_start=236
  _globals['_RESERVATION']._serialized_end=390
  _globals['_CHECKRESERVATIONRESPONSE']._serialized_start=392
  _globals['_CHECKRESERVATIONRESPONSE']._serialized_end=509
  _globals['_GRPCTICKETINGSERVICE']._serialized_start=512
  _globals['_GRPCTICKETINGSERVICE']._serialized_end=714
# @@protoc_insertion_point(module_scope)
