# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc  # type: ignore
import warnings

import app.infrastructure.grpc.user_pb2 as user__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in user_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class GrpcUserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEventOrganizer = channel.unary_unary(
            "/user.GrpcUserService/GetEventOrganizer",
            request_serializer=user__pb2.GetEventOrganizerRequest.SerializeToString,
            response_deserializer=user__pb2.GetEventOrganizerResponse.FromString,
            _registered_method=True,
        )
        self.GetSystemUser = channel.unary_unary(
            "/user.GrpcUserService/GetSystemUser",
            request_serializer=user__pb2.GetSystemUserRequest.SerializeToString,
            response_deserializer=user__pb2.GetSystemUserResponse.FromString,
            _registered_method=True,
        )
        self.GetReferralInfo = channel.unary_unary(
            "/user.GrpcUserService/GetReferralInfo",
            request_serializer=user__pb2.GetReferralInfoRequest.SerializeToString,
            response_deserializer=user__pb2.GetReferralInfoResponse.FromString,
            _registered_method=True,
        )
        self.GetUserContactInfo = channel.unary_unary(
            "/user.GrpcUserService/GetUserContactInfo",
            request_serializer=user__pb2.GetUserContactInfoRequest.SerializeToString,
            response_deserializer=user__pb2.GetUserContactInfoResponse.FromString,
            _registered_method=True,
        )
        self.GetUserDefaultTenant = channel.unary_unary(
            "/user.GrpcUserService/GetUserDefaultTenant",
            request_serializer=user__pb2.GetUserDefaultTenantRequest.SerializeToString,
            response_deserializer=user__pb2.GetUserDefaultTenantResponse.FromString,
            _registered_method=True,
        )


class GrpcUserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetEventOrganizer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetSystemUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetReferralInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetUserContactInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetUserDefaultTenant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_GrpcUserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetEventOrganizer": grpc.unary_unary_rpc_method_handler(
            servicer.GetEventOrganizer,
            request_deserializer=user__pb2.GetEventOrganizerRequest.FromString,
            response_serializer=user__pb2.GetEventOrganizerResponse.SerializeToString,
        ),
        "GetSystemUser": grpc.unary_unary_rpc_method_handler(
            servicer.GetSystemUser,
            request_deserializer=user__pb2.GetSystemUserRequest.FromString,
            response_serializer=user__pb2.GetSystemUserResponse.SerializeToString,
        ),
        "GetReferralInfo": grpc.unary_unary_rpc_method_handler(
            servicer.GetReferralInfo,
            request_deserializer=user__pb2.GetReferralInfoRequest.FromString,
            response_serializer=user__pb2.GetReferralInfoResponse.SerializeToString,
        ),
        "GetUserContactInfo": grpc.unary_unary_rpc_method_handler(
            servicer.GetUserContactInfo,
            request_deserializer=user__pb2.GetUserContactInfoRequest.FromString,
            response_serializer=user__pb2.GetUserContactInfoResponse.SerializeToString,
        ),
        "GetUserDefaultTenant": grpc.unary_unary_rpc_method_handler(
            servicer.GetUserDefaultTenant,
            request_deserializer=user__pb2.GetUserDefaultTenantRequest.FromString,
            response_serializer=user__pb2.GetUserDefaultTenantResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "user.GrpcUserService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("user.GrpcUserService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class GrpcUserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetEventOrganizer(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/user.GrpcUserService/GetEventOrganizer",
            user__pb2.GetEventOrganizerRequest.SerializeToString,
            user__pb2.GetEventOrganizerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetSystemUser(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/user.GrpcUserService/GetSystemUser",
            user__pb2.GetSystemUserRequest.SerializeToString,
            user__pb2.GetSystemUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetReferralInfo(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/user.GrpcUserService/GetReferralInfo",
            user__pb2.GetReferralInfoRequest.SerializeToString,
            user__pb2.GetReferralInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetUserContactInfo(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/user.GrpcUserService/GetUserContactInfo",
            user__pb2.GetUserContactInfoRequest.SerializeToString,
            user__pb2.GetUserContactInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetUserDefaultTenant(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/user.GrpcUserService/GetUserDefaultTenant",
            user__pb2.GetUserDefaultTenantRequest.SerializeToString,
            user__pb2.GetUserDefaultTenantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
