# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"3\n\x1bGetUserDefaultTenantRequest\x12\x14\n\x0cuser_auth_id\x18\x01 \x01(\t\"b\n\x1cGetUserDefaultTenantResponse\x12\x12\n\x05\x65rror\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x16\n\ttenant_id\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x08\n\x06_errorB\x0c\n\n_tenant_id\"1\n\x19GetUserContactInfoRequest\x12\x14\n\x0cuser_auth_id\x18\x01 \x01(\t\"\x87\x01\n\x1aGetUserContactInfoResponse\x12\x12\n\x05\x65rror\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x12\n\x05phone\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x13\n\x06\x64\x65vice\x18\x04 \x01(\tH\x02\x88\x01\x01\x42\x08\n\x06_errorB\x08\n\x06_phoneB\t\n\x07_device\"(\n\x18GetEventOrganizerRequest\x12\x0c\n\x04slug\x18\x01 \x01(\t\"J\n\x19GetEventOrganizerResponse\x12\x12\n\x05\x65rror\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x0f\n\x07user_id\x18\x02 \x01(\tB\x08\n\x06_error\"\x16\n\x14GetSystemUserRequest\"F\n\x15GetSystemUserResponse\x12\x12\n\x05\x65rror\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x0f\n\x07user_id\x18\x02 \x01(\tB\x08\n\x06_error\")\n\x16GetReferralInfoRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"Y\n\x17GetReferralInfoResponse\x12\x12\n\x05\x65rror\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x07user_id\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x08\n\x06_errorB\n\n\x08_user_id2\xb9\x03\n\x0fGrpcUserService\x12T\n\x11GetEventOrganizer\x12\x1e.user.GetEventOrganizerRequest\x1a\x1f.user.GetEventOrganizerResponse\x12H\n\rGetSystemUser\x12\x1a.user.GetSystemUserRequest\x1a\x1b.user.GetSystemUserResponse\x12N\n\x0fGetReferralInfo\x12\x1c.user.GetReferralInfoRequest\x1a\x1d.user.GetReferralInfoResponse\x12W\n\x12GetUserContactInfo\x12\x1f.user.GetUserContactInfoRequest\x1a .user.GetUserContactInfoResponse\x12]\n\x14GetUserDefaultTenant\x12!.user.GetUserDefaultTenantRequest\x1a\".user.GetUserDefaultTenantResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETUSERDEFAULTTENANTREQUEST']._serialized_start=20
  _globals['_GETUSERDEFAULTTENANTREQUEST']._serialized_end=71
  _globals['_GETUSERDEFAULTTENANTRESPONSE']._serialized_start=73
  _globals['_GETUSERDEFAULTTENANTRESPONSE']._serialized_end=171
  _globals['_GETUSERCONTACTINFOREQUEST']._serialized_start=173
  _globals['_GETUSERCONTACTINFOREQUEST']._serialized_end=222
  _globals['_GETUSERCONTACTINFORESPONSE']._serialized_start=225
  _globals['_GETUSERCONTACTINFORESPONSE']._serialized_end=360
  _globals['_GETEVENTORGANIZERREQUEST']._serialized_start=362
  _globals['_GETEVENTORGANIZERREQUEST']._serialized_end=402
  _globals['_GETEVENTORGANIZERRESPONSE']._serialized_start=404
  _globals['_GETEVENTORGANIZERRESPONSE']._serialized_end=478
  _globals['_GETSYSTEMUSERREQUEST']._serialized_start=480
  _globals['_GETSYSTEMUSERREQUEST']._serialized_end=502
  _globals['_GETSYSTEMUSERRESPONSE']._serialized_start=504
  _globals['_GETSYSTEMUSERRESPONSE']._serialized_end=574
  _globals['_GETREFERRALINFOREQUEST']._serialized_start=576
  _globals['_GETREFERRALINFOREQUEST']._serialized_end=617
  _globals['_GETREFERRALINFORESPONSE']._serialized_start=619
  _globals['_GETREFERRALINFORESPONSE']._serialized_end=708
  _globals['_GRPCUSERSERVICE']._serialized_start=711
  _globals['_GRPCUSERSERVICE']._serialized_end=1152
# @@protoc_insertion_point(module_scope)
