#!/bin/bash
set -euo pipefail

echo "=== Payment Service Entrypoint: Creating .env from Vault Secrets ==="

ENV_FILE="/app/.env"

# Function to create .env file from vault secrets
create_env_file() {
    echo "Creating .env file from Vault secrets..."
    
    # Initialize/clear the .env file
    cat > "$ENV_FILE" << EOF
# Generated .env file from Vault secrets
# Created at: $(date)
# Do not edit this file manually - it will be overwritten

EOF
    
    # Check if vault secrets directory exists
    if [ ! -d "/vault/secrets" ]; then
        echo "WARNING: /vault/secrets directory does not exist."
        return 0
    fi
    
    # Check if directory is readable
    if [ ! -r "/vault/secrets" ]; then
        echo "ERROR: /vault/secrets directory is not readable"
        return 1
    fi
    
    local secrets_loaded=0
    
    for secret_file in /vault/secrets/*; do
        # Skip if no files match the pattern
        [ ! -e "$secret_file" ] && continue
        
        if [ -f "$secret_file" ] && [ -r "$secret_file" ]; then
            echo "Processing secret file: ${secret_file}"
            
            # Add section header to .env file
            echo "" >> "$ENV_FILE"
            echo "# Variables from $(basename "$secret_file")" >> "$ENV_FILE"
            
            # Create temp file for processing
            temp_file=$(mktemp)
            
            # Remove comments and empty lines, handle different line endings
            sed -e '/^[[:space:]]*#/d' -e '/^[[:space:]]*$/d' -e 's/\r$//' "$secret_file" > "$temp_file"
            
            # Check if temp file has content
            if [ ! -s "$temp_file" ]; then
                echo "  WARNING: No valid content found in $secret_file after processing"
                rm -f "$temp_file"
                continue
            fi
            
            local vars_from_file=0
            
            # Process each line
            while IFS= read -r line || [ -n "$line" ]; do
                [ -z "$line" ] && continue
                
                # Skip lines without '='
                [[ "$line" != *"="* ]] && {
                    echo "  WARNING: Skipping invalid line (no '='): $line"
                    continue
                }
                
                # Split on first '=' only
                key="${line%%=*}"
                value="${line#*=}"
                
                # Trim whitespace from key and value
                key=$(echo "$key" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
                value=$(echo "$value" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
                
                # Skip empty keys
                [ -z "$key" ] && {
                    echo "  WARNING: Empty key found, skipping line: $line"
                    continue
                }
                
                # Validate key format (basic shell variable name rules)
                if [[ ! "$key" =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]]; then
                    echo "  WARNING: Invalid variable name '$key', skipping"
                    continue
                fi
                
                # Add to .env file
                echo "$key=\"$value\"" >> "$ENV_FILE"
                vars_from_file=$((vars_from_file + 1))
                secrets_loaded=$((secrets_loaded + 1))
            done < "$temp_file"
            
            rm -f "$temp_file"
            echo "  Added $vars_from_file variables from $(basename "$secret_file")"
        fi
    done
    
    if [ $secrets_loaded -eq 0 ]; then
        echo "WARNING: No valid secrets were processed from /vault/secrets/"
    else
        echo "Processed $secrets_loaded total variables from Vault secrets"
    fi
    
    return 0
}

# Create the .env file
if ! create_env_file; then
    echo "ERROR: Failed to create .env file from Vault secrets"
    exit 1
fi

# Display the generated .env file (with sensitive values masked)
echo ""
echo "=== Generated .env File Preview ==="
if [ -f "$ENV_FILE" ]; then
    echo "File size: $(wc -l < "$ENV_FILE") lines"
    echo "Preview (sensitive values masked):"
    while IFS= read -r line || [ -n "$line" ]; do
        # Skip comments and empty lines for preview
        [[ "$line" =~ ^[[:space:]]*# ]] && continue
        [[ "$line" =~ ^[[:space:]]*$ ]] && continue
        
        if [[ "$line" == *"="* ]]; then
            key="${line%%=*}"
            value="${line#*=}"
            
            case "$key" in
                *URL*|*_URL|*PASSWORD*|*SECRET*|*KEY*|*TOKEN*)
                    echo "  $key=***"
                    ;;
                *)
                    echo "  $line"
                    ;;
            esac
        fi
    done < "$ENV_FILE"
    
    echo "✓ .env file successfully created at $ENV_FILE"
else
    echo "✗ .env file was not created"
    exit 1
fi

./init.sh

exec "$@"