"""update wallets table

Revision ID: 25f99d13f13d
Revises: 46cbae6b676f
Create Date: 2025-12-06 17:59:45.394368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25f99d13f13d'
down_revision: Union[str, Sequence[str], None] = '46cbae6b676f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('bank_details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'bank_details')
    # ### end Alembic commands ###
