"""init

Revision ID: 27b1f13828e5
Revises: 
Create Date: 2025-11-28 22:49:07.212321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27b1f13828e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charge_settings',
    sa.Column('charge_setting_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('charge_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('charge_setting_id', name=op.f('pk_charge_settings')),
    sa.UniqueConstraint('charge_type', name=op.f('uq_charge_settings_charge_type'))
    )
    op.create_table('charge_setting_versions',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('tiers', sa.JSON(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('change_reason', sa.String(), nullable=True),
    sa.Column('charge_setting_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['charge_setting_id'], ['charge_settings.charge_setting_id'], name=op.f('fk_charge_setting_versions_charge_setting_id_charge_settings'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('version_id', name=op.f('pk_charge_setting_versions')),
    sa.UniqueConstraint('charge_setting_id', 'version_number', name='uq_charge_setting_version_number')
    )
    op.create_index('ix_charge_setting_active_version', 'charge_setting_versions', ['charge_setting_id', 'effective_from', 'effective_until'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_charge_setting_active_version', table_name='charge_setting_versions')
    op.drop_table('charge_setting_versions')
    op.drop_table('charge_settings')
    # ### end Alembic commands ###
