"""txn can have a parent

Revision ID: 46cbae6b676f
Revises: 2c524ab033ca
Create Date: 2025-12-02 00:40:36.748449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46cbae6b676f'
down_revision: Union[str, Sequence[str], None] = '2c524ab033ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_transactions_parent_id_transactions'), 'transactions', 'transactions', ['parent_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_transactions_parent_id_transactions'), 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'parent_id')
    # ### end Alembic commands ###
