"""update transactions

Revision ID: 63a0498aee24
Revises: 9ca4cd3e8bee
Create Date: 2025-12-09 07:44:54.733803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63a0498aee24'
down_revision: Union[str, Sequence[str], None] = '9ca4cd3e8bee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('delayed_settlement_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'delayed_settlement_until')
    # ### end Alembic commands ###
