"""update txn_pin column

Revision ID: 9ca4cd3e8bee
Revises: 25f99d13f13d
Create Date: 2025-12-06 19:22:22.995263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ca4cd3e8bee'
down_revision: Union[str, Sequence[str], None] = '25f99d13f13d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallets', 'txn_pin',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallets', 'txn_pin',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=4),
               existing_nullable=True)
    # ### end Alembic commands ###
