"""create wallet table

Revision ID: abd2035efd10
Revises: fbf70f68e888
Create Date: 2025-12-01 03:19:09.065987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abd2035efd10'
down_revision: Union[str, Sequence[str], None] = 'fbf70f68e888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('pending_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('txn_pin', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallets'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallets')
    # ### end Alembic commands ###
