"""update charge settings version table

Revision ID: b28ee141c721
Revises: 63a0498aee24
Create Date: 2026-03-02 18:38:34.076191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b28ee141c721'
down_revision: Union[str, Sequence[str], None] = '63a0498aee24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charge_setting_versions', sa.Column('allow_overlap', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('charge_setting_versions', sa.Column('overlap_strategy', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charge_setting_versions', 'overlap_strategy')
    op.drop_column('charge_setting_versions', 'allow_overlap')
    # ### end Alembic commands ###
